### ISSUE TITLE
xscale dtrend giving error 'DataArray' object has no attribute 'view'

### ISSUE THREAD

**Issue by diptiSH** [serazing/xscale#19]
I want to detrend a 3D xarray object but it is giving an error  details are as follows -

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1037282/2152048850.py in <module>
      1 ### Detrend
----> 2 CRES_RSC_dt=detrend(CRES_RSC)
      3 CRES_RSC_dt

/tmp/ipykernel_1037282/1210698701.py in detrend(x)
      4 
      5 def detrend(x):
----> 6     return xfit.detrend(x, dim='time',type='linear')
      7 
      8 

~/.conda/envs/Allpython/lib/python3.9/site-packages/xscale-0.1.dev0+35.ga804866-py3.9.egg/xscale/signal/fitting.py in detrend(data, dim, type)
    183 	"""
    184         if isinstance(data, xr.DataArray):
--> 185                 data_trend = trend(data, dim=dim, type=type)
    186                 data_detrended = data - data_trend
    187         elif isinstance(data, xr.Dataset):

~/.conda/envs/Allpython/lib/python3.9/site-packages/xscale-0.1.dev0+35.ga804866-py3.9.egg/xscale/signal/fitting.py in trend(obj, dim, type)
    148                 # Use the 1e-9 to scale nanoseconds to seconds (by default, xarray use
    149                 # datetime in nanoseconds
--> 150                 t = pd.to_numeric(coord) * 1e-9
    151         else:
    152                 t = coord

~/.conda/envs/Allpython/lib/python3.9/site-packages/pandas/core/tools/numeric.py in to_numeric(arg, errors, downcast)
    177         pass
    178     elif is_datetime_or_timedelta_dtype(values_dtype):
--> 179         values = values.view(np.int64)
    180     else:
    181         values = ensure_object(values)

~/.conda/envs/Allpython/lib/python3.9/site-packages/xarray/core/common.py in __getattr__(self, name)
    237                 with suppress(KeyError):
    238                     return source[name]
--> 239         raise AttributeError(
    240             f"{type(self).__name__!r} object has no attribute {name!r}"
    241         )

AttributeError: 'DataArray' object has no attribute 'view'

**Comment by serazing** [comment]
Hi, xarray has now the polyfit method that should do the job correctly. I'll suggest to give it a try, it works fine for the things I had to do recently. Cheers

**Comment by diptiSH** [comment]
Thanks @serazing. yes, it works.
