### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by rabernat** [serazing/xscale#6]
I see you are only testing with python 2...does xscale support python 3? I want to try it, but I need to set up an environment first. I would prefer python 3 if possible.

**Comment by rabernat** [comment]
update: it definitely does NOT support python 3.5.

**Comment by serazing** [comment]
Agreed, I will add a support for python 3.5. Xscale tests principally fail with python 3 because of the use of `basestring` in `_utils`. I will correct that soon.

**Comment by serazing** [comment]
Ok, Xscale tests now work with Python 3.5 (see Travis CI). I will keep the discussion opened since the code coverage is only 50% for the moment. Let me know if there are other issues with Python 3.

**Comment by rabernat** [comment]
Was there a PR to fix this? Or did you just push directly?

**Comment by serazing** [comment]
I have pushed it directly but I think I should stop doing that, at least for issues in order to track changes. I reckon still lack of experience with github.
